### ISSUE TITLE
width descriptor should specify the width of the image

### ISSUE THREAD

**Issue by tobaco** [rolandtoth/MarkupSrcSet#2]
Hi,

i wanted to use the MarkupSrcSet module but noticed it's output differs from the specification of `srcset` and `sizes`.

The `w` descriptor should specify the width of the image and not a breakpoint. See https://ericportis.com/posts/2014/srcset-sizes/

> `srcset` takes a comma-separated list of URLs for the available versions of the image; each image’s width is specified using the `w` descriptor. So if you “Save for Web…” at 1024 × 768, mark that source up in `srcset` as `1024w`.

With the implementation right now, the browsers will assume the wrong image dimensions.

I think, the breakpoint setting could be left out and an option for the `sizes` attribute for each preset should be introduced. 

this could look like this:

```
{
    "hero": {
        "srcset": [
              [360, 270], [640, null], [1080, null], [1920, null]
       ],
        "sizes": "(min-width: 36em) 33.3vw, 100vw",
    }
}
```

So the output would look like this:

````
<img 
    src="image.360x0.jpg" 
    srcset="image.360x0.jpg 360w, image.640x0.jpg 640w, image.1080x0.jpg 1080w, image.1920x0.jpg 1920w" 
    sizes="(min-width: 36em) 33.3vw, 100vw" 
    alt="">
```

What do you think?

**Comment by rolandtoth** [comment]
Thanks for the clarification - yes, this would be a better approach. There was also a request about it recently in the forums.

I'm also considering to add the markup inside the src tag, like this:

`<img src="<php echo $pages->get(1)->featured_image->srcset('hero'); ?>">`

This wouldn't make IDEs complain about missing src tags on images. 
Even I often start to write srcset code like this and have to consult the docs to fix.

The downside is that one would have to always use double quotes because the markup would add the closing quote for src and the start quote for the srcset and sizes (note the missing start/end quotes):

`small.jpg" srcset="..." sizes="...`

Plus I'm about to remove the feature to add the "lazyload" class. It's fine if someone needs only this class but it's a problem if multiple classes are needed.

Thoughts?

**Comment by tobaco** [comment]
hm,

i see two options here:
the first one would be to use the module as it is right now:

```
<img <?php echo $page->featured_image->srcset('featured-image'); ?>>
```

and the second one would be the possibility to output single attributes:

```
<img src="<?php echo $page->featured_image->srcsetattr('featured-image', 'src'); ?>" srcset="<?php echo $page->featured_image->srcsetattr('featured-image', 'srcset'); ?>" sizes="<?php echo $page->featured_image->srcsetattr('featured-image', 'sizes'); ?>">
```

_`srcsetattr` could be named better …_

this way the developer could choose.

**Comment by rolandtoth** [comment]
The second one is a no-go for me, too wide :) Perhaps a module option could be added to switch quote type.

I'm also about to simplify the way image sets are stored, like this:

```
"hero": {
    "srcset": "514x200, 2, 3",
    "sizes": "(min-width: 36em) 33.3vw, 100vw"
}
```

So no start/end curly quotes, plus size arrays are in WxH format.

**Comment by rolandtoth** [comment]
I've made some progress but some testing is needed beforehands. 

I'm curious what do you think about this syntax for image sets:

```
hero: 360x240, 2, 3
featured: 360x240, 2, 3 | auto
gallery: 360x240, 2, 3 | (min-width: 36em) 33.3vw, 100vw
```

I think this is self-explanatory: `name: set1 set2 ... | sizes`.

**Comment by tobaco** [comment]
Looks good to me.
Is the hero and featured in your example the same, regarding the sizes attribute?

And is it possible to just specify the width of the image? E.g. like this:

```
gallery: 360x0, 2, 3 | (min-width: 36em) 33.3vw, 100vw
```

Thanks for your work on this!

**Comment by rolandtoth** [comment]
hero vs featured: I don't know if I should allow no size attribute, so make it too fall back to "auto" if it's not specified.

Sure, 360x0 is allowed.

I'm hesitant about the syntax above because the previous is easier to extend, eg. adding extra settings, eg. use transparent gif uri placeholder. Not that I'm about to implement this now, I will be happy if all these will come together nicely :)

**Comment by rolandtoth** [comment]
v0.1 fixes the descriptor vs width issue and introduces a new syntax so better read the docs :)
